# docker build and deploy to k8s pipeline
# last modified nov 13 2019

image: docker:latest
services:
#  - docker:dind
   - docker:19.03.0-dind

stages:
  - build
  - deploy

variables:
  DOCKER_HOST: tcp://localhost:2375
  DOCKER_TLS_CERTDIR: ""
  CONTAINER_IMAGE: docker.grepped.org/chattest:${CI_COMMIT_SHORT_SHA}

build:
  stage: build
  script:
    - echo docker username=${DOCKER_USER} password=${DOCKER_PASSWORD}
    - docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD} docker.grepped.org
    - docker build -t ${CONTAINER_IMAGE} .
    - docker tag ${CONTAINER_IMAGE} ${CONTAINER_IMAGE}
    - docker tag ${CONTAINER_IMAGE} docker.grepped.org/chattest:latest
    - docker push ${CONTAINER_IMAGE}

deploy:
  stage: deploy
  image: dtzar/helm-kubectl
  script:
    - kubectl config set-cluster k8s --server="${SERVER}"
    - kubectl config set clusters.k8s.certificate-authority-data ${CERTIFICATE_AUTHORITY_DATA}
    - kubectl config set-credentials gitlab --token="${USER_TOKEN}"
    - kubectl config set-context default --cluster=k8s --user=gitlab
    - kubectl config use-context default
    - sed -i "s/<VERSION>/${CI_COMMIT_SHORT_SHA}/g" deployment.yaml
    - kubectl apply -f deployment.yaml

# EOF
