apiVersion: apps/v1
kind: Deployment
metadata:
  name: chattest
  labels:
    app: chattest
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chattest
  template:
    metadata:
      labels:
        app: chattest
    spec:
      containers:
        - name: chattest
          image: docker.grepped.org/chattest:<VERSION>
          ports:
            - containerPort: 8080
