// Code generated by "stringer -type=OpCode"; DO NOT EDIT

package webchat

import "fmt"

const _OpCode_name = "MessageOpHistoryOpNoticeOpJoinOpNickOp"

var _OpCode_index = [...]uint8{0, 9, 18, 26, 32, 38}

func (i OpCode) String() string {
	if i < 0 || i >= OpCode(len(_OpCode_index)-1) {
		return fmt.Sprintf("OpCode(%d)", i)
	}
	return _OpCode_name[_OpCode_index[i]:_OpCode_index[i+1]]
}
