apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: webchat
  labels:
    app: webchat
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: webchat
    spec:
      containers:
      - name: webchat
        image: sigmonsays/webchat:latest
        ports:
          - containerPort: 8080
        resources:
          limits:
           memory: 256Mi
          requests:
           memory: 128Mi
